version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dou-app
    volumes:
      - .:/var/www
    depends_on:
      - db
      - rabbitmq
    environment:
      APP_ENV: local
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    expose:
      - 9000

  web:
    image: nginx:latest
    container_name: dou-nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: dou-db
    restart: always
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dou-worker
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=60
    volumes:
      - .:/var/www
    depends_on:
      - app
      - rabbitmq
      - db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: dou-rabbit
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  adminer:
    image: adminer
    container_name: dou-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
